service: aws-node-github-webhook-listener
provider:
  name: aws
  runtime: nodejs6.10
  environment:
    GITHUB_WEBHOOK_SECRET: wow-sls-this-is-bad
functions:
  githubWebhookListener:
    handler: index.handler
    events:
      - http:
          path: webhook
          method: post
          cors: true
    runtime: nodejs8.10